# package.json repo à changer

tasks:
  - name: ts-node install globally
    init: npm install -g ts-node

  - name: install typescript dependency
    init: yarn add -d typescript

  - name: install @typescript-eslint/eslint-plugin dependency
    init: yarn add -d @typescript-eslint/eslint-plugin

  - name: install @typescript-eslint/parser dependency
    init: yarn add -d @typescript-eslint/parser

  - name: install eslint dependency
    init: yarn add -d eslint

  - name: install jest-cucumber dependency
    init: yarn add -d jest-cucumber

  - name: Install node dependencies
    init: yarn

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-ceintl.vscode-language-pack-fr
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - graphql.vscode-graphql
    - kavod-io.vscode-jest-test-adapter
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - yatki.vscode-surround
    - bradlc.vscode-tailwindcss
    - hbenl.vscode-test-explorer
    - gruntfuggly.todo-tree
    - gamunu.vscode-yarn
    - fabiospampinato.vscode-todo-plus
