tasks:
  - name: ts-node install globally
    init: npm install -g ts-node
  - name: Install node dependencies
    init: yarn

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-ceintl.vscode-language-pack-fr
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - graphql.vscode-graphql
    - kavod-io.vscode-jest-test-adapter
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - yatki.vscode-surround
    - bradlc.vscode-tailwindcss
    - hbenl.vscode-test-explorer
    - gruntfuggly.todo-tree
    - gamunu.vscode-yarn
    - fabiospampinato.vscode-todo-plus
