# package.json repo à changer

tasks:
  - name: Configuration
    init: |
      cd .gitpod-config
      bash bash.sh
      node bash.js
      cd ..
      yarn run prettier

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-ceintl.vscode-language-pack-fr
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - graphql.vscode-graphql
    - kavod-io.vscode-jest-test-adapter
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - yatki.vscode-surround
    - bradlc.vscode-tailwindcss
    - hbenl.vscode-test-explorer
    - fabiospampinato.vscode-todo-plus
    - dbaeumer.vscode-eslint
    - tabnine.tabnine-vscode
    - codezombiech.gitignore
    - foxundermoon.shell-format
    - redhat.vscode-xml
