# package.json repo à changer

tasks:
  - name: Configuration
    before: bash .gitpod-config/globalDependencies.sh
    init: |
      bash .gitpod-config/dependencies.sh
      node .gitpod-config/package.js
      gp sync-done config
      
  - name: Creation of branches
    init: |
      gp sync-await config
      bash .gitpod-config/git_branches.sh
      gp sync-done branches
      
  - name: Clean
    init: |
      gp sync-await branches
      bash .gitpod-config/cleanYaml.sh
    
vscode:
  extensions:
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - graphql.vscode-graphql
    - kavod-io.vscode-jest-test-adapter
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - yatki.vscode-surround
    - bradlc.vscode-tailwindcss
    - hbenl.vscode-test-explorer
    - fabiospampinato.vscode-todo-plus
    - dbaeumer.vscode-eslint
    - codezombiech.gitignore
    - foxundermoon.shell-format
    - redhat.vscode-xml
    - hbenl.test-adapter-converter
